### ISSUE TITLE
Keyboard case/wrist rest compatability

### ISSUE THREAD

**Issue by psaju** [null-ll/basketweave#11]
First od all, thank you for releasing this keyboard! I found it very enjoyable to build and to use.

I would like to ask about the shape of the keyboard - is it identical to any existing keyboard, like the Alice or Keychron Q8? I'm having trouble finding a wrist rest and/or case that would fit and cannot find any definitive answers.

**Comment by null-ll** [comment]
Sorry, the shape is not identical to any other existing boards that I know of. There are acrylic cases available from a few sellers online, though they are mostly custom order.
