### ISSUE TITLE
D72 is shown on PCB, but never referenced in build guide.

### ISSUE THREAD

**Issue by lou00011** [null-ll/basketweave#5]
Above rotary encoder is D72. D72 is never referenced in the build guide, however D71 appears in Step 3, but I cannot find it in on the actual board.

Can you confirmed that this is a typo? That in addition to D1-D68 for 1n4148 diode, you are supposed to use it for slot above rotary encoder?

**Comment by null-ll** [comment]
Yes, the slot above the rotary encoder is for a 1n4148 diode. The label D72 was a mistake from an earlier version of the board and was replaced with D71.

**Comment by lou00011** [comment]
Thanks, that clarifies it.
