### ISSUE TITLE
bootloader error

### ISSUE THREAD

**Issue by F1hone** [null-ll/basketweave#8]
hello，me again
Sorry to bother you..
I encountered a little problem when flashing the boot loader, when I try to use qmk msys to make the hex file of the bootloader, an error will be reported, resulting in I can't flash in, it's been bugging me for days,

**Comment by F1hone** [comment]
This is the information of the terminal,
please help me to see it, if you can give me a little help, I will be very grateful to you,
{I use usbasp},thanks a lot

[CHK@DESKTOP-3QEGFU6 32a]$ cd /m/Desktop/USBaspLoader-atmega32a
[CHK@DESKTOP-3QEGFU6 USBaspLoader-atmega32a]$ make
.
.
======>BUILDING BOOTLOADER FIRMWARE
.
make[1]: 进入目录“/m/Desktop/USBaspLoader-atmega32a/firmware”
main.c: In function 'main':
: warning: function declared 'noreturn' has a 'return' statement
.
.
.
!!!ATTANTION!!!
(data+text) MUST fit into your MCUs bootloader section
.
text data bss dec hex filename
2136 6 55 2197 895 main.elf
.
.
.
make[1]: 离开目录“/m/Desktop/USBaspLoader-atmega32a/firmware”
.
.
======>BUILDING BOOTLOADER UPDATER (EXPERIMENTAL)
.
make[1]: 进入目录“/m/Desktop/USBaspLoader-atmega32a/updater”
In file included from updater.c:8:
usbasploader.h:20:14: warning: duplicate 'const' declaration specifier [-Wduplicate-decl-specifier]
extern const const uint16_t usbasploader[SIZEOF_new_firmware>>1] PROGMEM;
^~~~~
updater.c:53:4: warning: #warning I do not know where new "bootloader__do_spm" is located - assuming "NEW_BOOTLOADER_ADDRESS+(funcaddr___bootloader__do_spm % SPM_PAGESIZE)" [-Wcpp]
#warning I do not know where new "bootloader__do_spm" is located - assuming "NEW_BOOTLOADER_ADDRESS+(funcaddr___bootloader__do_spm % SPM_PAGESIZE)"
^~~~~~~
updater.c:61:4: warning: #warning "TEMP_SPM_PAGEADR" is not defined explicitly - will choose END OF FLASH ! [-Wcpp]
#warning "TEMP_SPM_PAGEADR" is not defined explicitly - will choose END OF FLASH !
^~~~~~~
.
.
text data bss dec hex filename
3102 2 0 3104 c20 updater.elf
.
make[1]: 离开目录“/m/Desktop/USBaspLoader-atmega32a/updater”
[CHK@DESKTOP-3QEGFU6 USBaspLoader-atmega32a]$

**Comment by null-ll** [comment]
There shouldn't be an issue. The firmware seems to have been built successfully, as shown in the first half of the output. The second half is not used in this board and can be ignored.

**Comment by F1hone** [comment]
Thank you for your reply,
I tried to use commands other than "make flash" to burn the bootloader into the chip, the result was successful,
Then I tried to build my own keyboard hex file using your bootloader for the 32a chip, and it failed. There are very few tutorials on how to customize the bootloader on the Internet. I can only learn from other people's firmware, but I still don't understand the meaning of many of the values. . This is too hard for me as a beginner, can you give me some guidance? Thank you very much.

**Comment by null-ll** [comment]
If you are able to successfully burn the bootloader onto the chip, the keyboard should be detected by QMK toolbox. You can just flash your keyboard hex file from there.
